### ISSUE TITLE
B2X transaction rejected

### ISSUE THREAD

**Issue by whizz** [ymgve/bitcoin_fork_claimer#16]
When trying to claim B2X, I am getting rejected and the transaction does not make it into mempool.

```
'reject' '\x02tx@Jnon-mandatory-script-verify-flag (Signature must use SIGHASH_FORKID_SHIFT)
```

**Comment by soul4soul** [comment]
I'm getting rejected B2X transactions too. I tried this for the first time yesterday 02/17
```---> 'mempool' (0 bytes)
<--- 'inv' (829 bytes)
        transaction: 4705137f99adb8cf9e428c935c514dc9451c9d7abe4ea03a8bf186a37ff5cdfb
        transaction: ef49b72054ffee2081471e4bb7ddc7104e2e2e5547af1c3293598e8912846feb
        transaction: 868a794b73082417abdb134c6c77cd1702120590c429eeedf7944c69780d6ce9
        transaction: a216247a3b8e68b924665f1d47dec1f5de7f1cdcac694cae910acece68a66fe7
        transaction: b1916366952fde04db9a9c7c1e1619676b6961868ff34d681e253b4329fbc2c4
        transaction: 3f582cd7f1d657a4f104f61d91819aa902a8466863689149573f5c6df1508ab4
        transaction: d8b106adcdfdfb996fca0b1f0c3e87e58f1d61557992ce0391bdd178b36658b3
        transaction: 22cb8bb5ec5528fff460fc4e7cd12ae947bde479723f68bcf3df9fc4daffb2b0
        transaction: be993cca8a42c6c39d709f21e129e88212066247f98fc8b527f5141b99cd336e
        transaction: 3df89ad031e28c46fcf9a873f1625a0eb8d9c24fe277d0d802f13859e01b7b63
        ...
        Not printing additional 13 transactions

        Our transaction was not found in the mempool.
Traceback (most recent call last):
  File "claimer.py", line 1131, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 502, in send_tx
    raise Exception("\tGiving up on transaction. Please verify that the inputs have not already been spent.")
Exception:      Giving up on transaction. Please verify that the inputs have not already been spent.```

**Comment by ymgve** [comment]
Should be fixed with https://github.com/ymgve/bitcoin_fork_claimer/commit/4752dbdc886a8871dd7958d7a9b305a0447843aa
