### ISSUE TITLE
problem with p key

### ISSUE THREAD

**Issue by horaclito** [ymgve/bitcoin_fork_claimer#23]
The scrypt doesn't recognize the key type when I introduce the p key.

Traceback (most recent call last):
  File "C:\bitcoin_fork_claimer\claimer.py", line 1101, in <module>
    get_txid(coin, args)
  File "C:\bitcoin_fork_claimer\claimer.py", line 346, in get_txid
    restofprogram(coin, args)
  File "C:\bitcoin_fork_claimer\claimer.py", line 961, in restofprogram
    keytype, privkey, pubkey, sourceh160, compressed = identify_keytype(args.wifkey, args.srcaddr)
  File "C:\bitcoin_fork_claimer\claimer.py", line 313, in identify_keytype
    raise Exception("Unable to identify key type!")
Exception: Unable to identify key type!

it is a segwit adress, starts with 3, and the pkey starts wit L.

Any idea about what is hapenning?

**Comment by ymgve** [comment]
What kind of segwit address is it? The script doesn't work with all kinds of segwit addresses, only the P2SH-P2WPKH ones.

**Comment by horaclito** [comment]
the adress starts with 3, so I assumed is P2SH. 
Googling I find could be a multisig wallet. I am pretty sure that in such a case it was created in electrum 2.1. It woud be a problem??

**Comment by ymgve** [comment]
The script does not support multisig at the moment. Need further details to find out why it fails.

**Comment by horaclito** [comment]
are u planning to add support for multisig?
if there is any particular detail I could provide, please tell me!
Thanks

**Comment by ymgve** [comment]
Do you know if it's multisig or segwit? How was the address created? What is the public address?

**Comment by horaclito** [comment]
Hi, I didn't see your questions before!
It is a multisig wallet. So it seems I won't be able to use the script.
I hope the scrypt will support multisig wallets soon!

**Comment by alternativshik** [comment]
Same issue for me. Can't claim from multisig wallet

**Comment by serevan** [comment]
Same problem

**Comment by ymgve** [comment]
Multisig is not supported at the moment. Might consider adding it in the future.
