### ISSUE TITLE
BTG transaction rejected

### ISSUE THREAD

**Issue by juancamilocanal** [ymgve/bitcoin_fork_claimer#44]
Hi, Im having problems claiming BTG, any help would be appreciated.

Connecting to ('btg1.stage.bitsane.com', 8338) ... SUCCESS, connected to ('164.132.121.47', 8338)
---> 'version' (93 bytes)
<--- 'version' (109 bytes)
     Version information:
	protocol version 70016
	services 13
	timestamp Tue May 22 12:15:58 2018
	user agent '/Bitcoin Gold:0.15.0.2/'
	block height 529591
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'addr' (31 bytes)
	Got peer address: 164.132.121.47:8338
<--- 'feefilter' (8 bytes)
	server requires minimum fee of 1000 satoshis
	our fee is >= minimum fee, so should be OK
<--- 'getdata' (37 bytes)
	Peer requesting transaction details for d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'tx' (218 bytes)
	SENT TRANSACTION: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
<--- 'getdata' (37 bytes)
	Received getdata without our txhash. The transaction may have been rejected.
	This script will retransmit the transaction and monitor the mempool for a few minutes before giving up.
<--- 'inv' (97815 bytes)
	transaction: f2f1711a25d5b14e930b3bafdc105ce6d136ed75112c5b56f3f596e4390e2739
	transaction: 0c06b486bb94187ed23e38629c5cbde0ee21181fc9bb0980cd312e058febe590
	transaction: c5277b2098a18a8bffbff11706db57c6a4e83c9648f0c88cbcf82fcdd4bd7aaf
	transaction: a9f7063ddf6ad47d30a56298a7261be5fc78acd58490034d2e648253e4007abc
	transaction: d43e736db88145f3aede5546cf93859badc6c5e111198be6369adb569dc34082
	transaction: 853d51e706f82ef952c9ec26e706e178dde6b900ec3dd219ceac9285a209737b
	transaction: 56b95c63208b290f8d2eac6f49ddf90d5206b39cf5753b9143af7549210c14e7
	transaction: f41aa64c7865433fe36f1b9e08b081f86c48322d7163db4b39c54187b3403192
	transaction: 3bc07708fcfe30e5211981fc869abb11d4f153e1a116a97d9346bab10c07926e
	transaction: fc2eae66a4c50f6ca597c17a7563744c0eef15889e3b798fdcc39fa2285de1d0
	...
	Not printing additional 2707 transactions

	Our transaction was not found in the mempool.
	Will retransmit and check again 4 more times.
<--- 'addr' (61 bytes)
	Got peer address: 110.10.189.189:8338
	Got peer address: 109.128.16.178:8338
<--- 'inv' (37 bytes)
	block: 000000002005dfd5c1656befd777faeadb4502aaf5b0e77879e30ab92c2c796f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (739746 bytes)
	Transaction not included in observed block.
<--- 'addr' (31 bytes)
	Got peer address: [2001:0678:053c:0002:0010:0000:0001:0103]:8338
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (218 bytes)
	Re-sent transaction: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'mempool' (0 bytes)
<--- 'inv' (97275 bytes)
	transaction: 48bfa144878edd8c6b08b8494cab7c0b2cd10599a647f2ffb1ceb06b21ddb049
	transaction: 8afd4b5c931dfcfebbfd8b448fbbcc74a345b37e757dc6cceaddebdc04ba3929
	transaction: ac40dc3f920004ec5ed0c79ca1437ae25e03b2e98d4e54eda077fbb55bcbe8af
	transaction: c576178f84f43ed596a46d3f681cd62183cb6fa945739af3dcc5608b801fde9c
	transaction: 82c86c7714dd99202deac6f35e2f70c54ebb41619f2bbb092d8d6bee2b310c81
	transaction: 181f2b1229a323919527868884b7e055c6eaef58e1348d85d6e75cf2bbfb2e60
	transaction: 60f2e717b0a1dac4ea9e3d1aa88df6867358ed28361722ba4866ca878d15f06f
	transaction: a4b310dd5392e25c87477d47ee9586d0b42a5c84421810356d60d83d5022a052
	transaction: fc5a17c6d56a0326526ad176202840a9400300db1162896483bb050004142ec2
	transaction: e7c0d5a6482ed7fba4d05519ac02b1b54e8bf5d99cd140fd823466d0e634ac9e
	...
	Not printing additional 2692 transactions

	Our transaction was not found in the mempool.
	Will retransmit and check again 3 more times.
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (218 bytes)
	Re-sent transaction: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'mempool' (0 bytes)
<--- 'inv' (97743 bytes)
	transaction: 48bfa144878edd8c6b08b8494cab7c0b2cd10599a647f2ffb1ceb06b21ddb049
	transaction: 8afd4b5c931dfcfebbfd8b448fbbcc74a345b37e757dc6cceaddebdc04ba3929
	transaction: 7a6a27cdaa7372a26383626fa7fb949219ebde7058bb238e3ce731322f706bc9
	transaction: ac40dc3f920004ec5ed0c79ca1437ae25e03b2e98d4e54eda077fbb55bcbe8af
	transaction: c576178f84f43ed596a46d3f681cd62183cb6fa945739af3dcc5608b801fde9c
	transaction: 82c86c7714dd99202deac6f35e2f70c54ebb41619f2bbb092d8d6bee2b310c81
	transaction: 181f2b1229a323919527868884b7e055c6eaef58e1348d85d6e75cf2bbfb2e60
	transaction: 60f2e717b0a1dac4ea9e3d1aa88df6867358ed28361722ba4866ca878d15f06f
	transaction: ca676bfb8ed5bc8657332a0ca032a41ea91b5ed323d42038a10000c3d2c4ea6b
	transaction: 70989e8e2adfe09e776b0d1fee5b7b6968d40aed4da5bac342c8a88e79738fb5
	...
	Not printing additional 2705 transactions

	Our transaction was not found in the mempool.
	Will retransmit and check again 2 more times.
<--- 'addr' (31 bytes)
	Got peer address: [2001:0000:9d38:78cf:043b:1839:dd09:a52f]:8338
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (218 bytes)
	Re-sent transaction: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'mempool' (0 bytes)
<--- 'inv' (98247 bytes)
	transaction: e6cf95330921d67c7bc50c7d7c5fbf3e33221143a23c12ff666b603f0963157e
	transaction: 48bfa144878edd8c6b08b8494cab7c0b2cd10599a647f2ffb1ceb06b21ddb049
	transaction: 8afd4b5c931dfcfebbfd8b448fbbcc74a345b37e757dc6cceaddebdc04ba3929
	transaction: 7a6a27cdaa7372a26383626fa7fb949219ebde7058bb238e3ce731322f706bc9
	transaction: ac3e3374fc0fb42996d9f014e0428381a652fdb8b5405b2f8a666e2c5c7394a2
	transaction: ad4fb23794a8ae4b004fac6240b10ed346f8c24c12832883c45dd0088f6f60f5
	transaction: ac40dc3f920004ec5ed0c79ca1437ae25e03b2e98d4e54eda077fbb55bcbe8af
	transaction: c576178f84f43ed596a46d3f681cd62183cb6fa945739af3dcc5608b801fde9c
	transaction: 82c86c7714dd99202deac6f35e2f70c54ebb41619f2bbb092d8d6bee2b310c81
	transaction: 181f2b1229a323919527868884b7e055c6eaef58e1348d85d6e75cf2bbfb2e60
	...
	Not printing additional 2719 transactions

	Our transaction was not found in the mempool.
	Will retransmit and check again 1 more times.
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (218 bytes)
	Re-sent transaction: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'mempool' (0 bytes)
<--- 'inv' (98751 bytes)
	transaction: e6cf95330921d67c7bc50c7d7c5fbf3e33221143a23c12ff666b603f0963157e
	transaction: 48bfa144878edd8c6b08b8494cab7c0b2cd10599a647f2ffb1ceb06b21ddb049
	transaction: 8afd4b5c931dfcfebbfd8b448fbbcc74a345b37e757dc6cceaddebdc04ba3929
	transaction: 7a6a27cdaa7372a26383626fa7fb949219ebde7058bb238e3ce731322f706bc9
	transaction: ac3e3374fc0fb42996d9f014e0428381a652fdb8b5405b2f8a666e2c5c7394a2
	transaction: ad4fb23794a8ae4b004fac6240b10ed346f8c24c12832883c45dd0088f6f60f5
	transaction: ac40dc3f920004ec5ed0c79ca1437ae25e03b2e98d4e54eda077fbb55bcbe8af
	transaction: c576178f84f43ed596a46d3f681cd62183cb6fa945739af3dcc5608b801fde9c
	transaction: 82c86c7714dd99202deac6f35e2f70c54ebb41619f2bbb092d8d6bee2b310c81
	transaction: a476f27e475260200bcea8953cb9dcfebd3443619f42d9581b2c852bf960a84a
	...
	Not printing additional 2733 transactions

	Our transaction was not found in the mempool.
	Will retransmit and check again 0 more times.
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (218 bytes)
	Re-sent transaction: d7f18f6cc671227e1522f78e9c8b5196bc29fe59e132607c9d67a8998b0a5b37
---> 'mempool' (0 bytes)
<--- 'inv' (99183 bytes)
	transaction: e6cf95330921d67c7bc50c7d7c5fbf3e33221143a23c12ff666b603f0963157e
	transaction: 48bfa144878edd8c6b08b8494cab7c0b2cd10599a647f2ffb1ceb06b21ddb049
	transaction: 8afd4b5c931dfcfebbfd8b448fbbcc74a345b37e757dc6cceaddebdc04ba3929
	transaction: 7a6a27cdaa7372a26383626fa7fb949219ebde7058bb238e3ce731322f706bc9
	transaction: ac3e3374fc0fb42996d9f014e0428381a652fdb8b5405b2f8a666e2c5c7394a2
	transaction: ad4fb23794a8ae4b004fac6240b10ed346f8c24c12832883c45dd0088f6f60f5
	transaction: ac40dc3f920004ec5ed0c79ca1437ae25e03b2e98d4e54eda077fbb55bcbe8af
	transaction: c576178f84f43ed596a46d3f681cd62183cb6fa945739af3dcc5608b801fde9c
	transaction: 82c86c7714dd99202deac6f35e2f70c54ebb41619f2bbb092d8d6bee2b310c81
	transaction: a476f27e475260200bcea8953cb9dcfebd3443619f42d9581b2c852bf960a84a
	...
	Not printing additional 2745 transactions

	Our transaction was not found in the mempool.
Traceback (most recent call last):
  File "claimer.py", line 1467, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 571, in send_tx
    raise Exception("\tGiving up on transaction. Please verify that the inputs have not already been spent.")
Exception: 	Giving up on transaction. Please verify that the inputs have not already been spent.

**Comment by juancamilocanal** [comment]
Also BCA with this error:

Traceback (most recent call last):
  File "claimer.py", line 1356, in <module>
    rawaddr = b58decode(destaddr)
  File "claimer.py", line 68, in b58decode
    n = n * 58 + b58ab.index(c)
ValueError: substring not found

**Comment by juancamilocanal** [comment]
Similar problem with LBTC and BCA

LBTC:
generated transaction b7b3c5b3c014852aa4d8f597051fcc0ce0fa951a2fc819821d9882c1f2eab2ed


Connecting to servers and pushing transaction
Please wait for a minute before stopping the script to see if it entered the server mempool.


Connecting to ('seed7.lbtc.io', 9333) ... 	Connection failed with: error(61, 'Connection refused')
	Will retry 100 more times.
Connecting to ('seed8.lbtc.io', 9333) ... SUCCESS, connected to ('47.52.25.236', 9333)
---> 'version' (93 bytes)
<--- 'version' (102 bytes)
     Version information:
	protocol version 70013
	services 13
	timestamp Wed May 23 05:10:44 2018
	user agent '/Satoshi:0.14.2/'
	block height 2579657
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'sendcmpct' (9 bytes)
<--- 'sendcmpct' (9 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'feefilter' (8 bytes)
	server requires minimum fee of 1000 satoshis
	our fee is >= minimum fee, so should be OK
<--- 'inv' (37 bytes)
	block: 7c2efa7ce2f6dc6a8b218b4c7f93e552f7eac8fcc09f8c9e84a2a682a048cb6b
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: e0d3989ef0dc7011e7c24823b81784bb8fe69018b94ada1a7c76d5f4a2db04c5
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: b85e70baf6acaf1059e3c36adeef2d46044534a3db4bbc2281e434f1ab267625
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 409d284533b0697e797c6decd908c4d2343f3e2d9a8dc22426941d5dc303a3d7
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 02214bfe78e6f500b578a49257af500547626bfb752cad84d52992e12da9de10
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: babbd603dcd62fd6634ff7117457d099b6d70d7e50760e9bced1848b18832680
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (1801 bytes)
	transaction: f6b8d04679625e26c94cc48816a0ef7abe70974ed445ad9088d5dfbfe1673065
	transaction: 0415e47566457e63ff78df9509da40044e9561fac172aad722ff912aa00d458e
	transaction: 7b69afcd59c54b56295f3c78cf10f002d9fbb5b457e4a8a027f3126bcbacffd4
	transaction: 50d6d54e3f5c40d41203e684550330fe1395c47af8b290876114f514320e50e1
	transaction: 5566cae75534592213eca6c6bf6dccac19c0260769b76c8871a96f54445e7975
	transaction: 3ee5e1213e6b7e8b66fd8ae1b130b14884ac0c15e25ae293e0268ad1d9464a68
	transaction: 902d37159c2a22dc6ce52d0011f59538167b7ef63cab01740a6be987484641fb
	transaction: a0d644c37eaf9d65e8257dd35c0684b2c9bb0d89d5d92626f7ceca02ddf61af9
	transaction: b7b3c5b3c014852aa4d8f597051fcc0ce0fa951a2fc819821d9882c1f2eab2ed
	transaction: 1c64e56f563e9758eb236611ed16219136233e8d5eb113353420ef76cb0ba6e6
	...
	Not printing additional 40 transactions

	OUR TRANSACTION IS IN THEIR MEMPOOL, TRANSACTION ACCEPTED! YAY!
	Consider leaving this script running until it detects the transaction in a block.
<--- 'inv' (37 bytes)
	block: d4cfe568094132bbbb168e5de9f35705b2f5d9cc0f04508a54c246f0c8a12a13
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 4c67a379d9a689ca7745446087aedec046f6c0c00a8ce57b769fd883832a0bfe
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: c8bcc6f8c313ed83ead307d52aa72a88e4f90a39b1b816441711994dd205c5e2
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 806f79a354fa3ad8794f2b0f1135f86ea2aeb75a5a2d34bdcec8e6215c67fd81
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 244f6f716ed2a57476aea04efae707f387276896b142394d19ffafce440116cc
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 4a4ec2c1dc665ccd92fa994bec48268571ff8c4fbf739d7225b55173f0ac389b
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: ef12435c3da568281b5ecafbcc9181a8ad335e34ccccc51413cbef44c0bdd60b
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 70584197729ea51eff41e155e20b45c9ae4092f273b591a464937a81c5527f6d
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: fe5e2798d2591a2e68ee008cafd23b1c0e850874398e3fbee0dceb9b04afbf1f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: af59b4418b6d8a0b81e95be0235481ff58d42eb084df6aee90dde8a3a16fc67f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 8538b5ca4b81abf45acf07d0e9a9e96262fb1b49a01a669964d633a3993f1651
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: f8cfc8c43c95e3d16eb96d7fcc27b0dc1bd879e0bd50c507206369740f611e10
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: f074faf69b86968320b923f2b1b86bd68dce4c56b82feb13ed9a218edaaa8249
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 9df46e823c1df9646fbf87525476597eaa5dd4a634ba461d4b4565e259bc3c92
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 32a7927c2cbad937a2bd4962639d698b6139ad3b9c25d36f4e0d90130b69fd64
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 9057851737588fe6fb18093a168194eb9119112515c5fd55084686640d3f9468
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 2d39b116a4279b92c9fad1af838f64e8abdf703d7866f7b62dd8666951d4795d
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 25522380efb847f9410f2c889ba92b4918fba5e7a7f720f82b3000774ef8ccd3
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: dee0d7588656e36621f4bc5ab9a75f2a76e1db861501b74c18df4c8e9f4b7e2d
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: c6bef6b634e88a6c18c42a3712f05991d96ed8e4b4ab44034f2dc71450008168
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 532c3ede5c63b1cd8f2bc8db23ad0d038872075faf57f829ef4f768752a0d66f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: b950b90e8748b61a02a73d3f843cb31636eba7bb6111aea38f46a206214c0b5d
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 7be87ffe7743b5f25248448bddf5514eb7767fbcde193b53cecd3401e392ad3f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 1f71b427d330d4f521b74cf51c35ff0bc29b292578c6392cfebca6ed56fe5ed7
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (308 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: c192a64140b5bc5cdd0900b4e813a4e02c56da639ec73b7430614fe04ee3721f
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 3c85070af95453e3dff4ef0890d8446479ee7c96114dd043018217a4e64c246a
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (309 bytes)
	Transaction not included in observed block.
<--- 'inv' (37 bytes)
	block: 3a00a2bde78f1abcf3d133dc0fb695aba56ac89ce2ad0df9d945b1643a714e9c
---> 'getdata' (37 bytes)
	requesting 1 blocks
^CTraceback (most recent call last):
  File "claimer.py", line 1467, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 479, in send_tx
    cmd, payload = client.recv_msg()
  File "claimer.py", line 450, in recv_msg
    header = recv_all(24)
  File "claimer.py", line 444, in recv_all
    temp = self.sc.recv(length - len(ret))
KeyboardInterrupt




BCA:
I am sending coins on the Bitcoin Atom network and I accept the risks
generated transaction 74bf1c6458c44eecec1a7d085e032b237a2b50e830ebaafb8be036057ce54c76


Connecting to servers and pushing transaction
Please wait for a minute before stopping the script to see if it entered the server mempool.


Connecting to ('seed.bitcoinatom.net', 7333) ... SUCCESS, connected to ('136.243.104.75', 7333)
---> 'version' (93 bytes)
<--- 'version' (102 bytes)
     Version information:
	protocol version 70020
	services 1037
	timestamp Wed May 23 05:10:14 2018
	user agent '/Satoshi:0.16.0/'
	block height 601922
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'addr' (31 bytes)
	Got peer address: 136.243.104.75:7333
<--- 'feefilter' (8 bytes)
	server requires minimum fee of 1000 satoshis
	our fee is >= minimum fee, so should be OK
<--- 'getdata' (37 bytes)
	Peer requesting transaction details for 74bf1c6458c44eecec1a7d085e032b237a2b50e830ebaafb8be036057ce54c76
---> 'tx' (217 bytes)
	SENT TRANSACTION: 74bf1c6458c44eecec1a7d085e032b237a2b50e830ebaafb8be036057ce54c76
<--- 'getdata' (37 bytes)
	Received getdata without our txhash. The transaction may have been rejected.
	This script will retransmit the transaction and monitor the mempool for a few minutes before giving up.
<--- 'inv' (37 bytes)
	block: 0000000000000001f5ced5539faebfd76b21dc67826b8c31a14baf147c30e343
---> 'getdata' (37 bytes)
	requesting 1 blocks
<--- 'block' (245 bytes)
	Transaction not included in observed block.
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (217 bytes)
	Re-sent transaction: 74bf1c6458c44eecec1a7d085e032b237a2b50e830ebaafb8be036057ce54c76
---> 'mempool' (0 bytes)
^CTraceback (most recent call last):
  File "claimer.py", line 1467, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 479, in send_tx
    cmd, payload = client.recv_msg()
  File "claimer.py", line 450, in recv_msg
    header = recv_all(24)
  File "claimer.py", line 444, in recv_all
    temp = self.sc.recv(length - len(ret))
KeyboardInterrupt

**Comment by ymgve** [comment]
I can not provide more support for these coins unless you provide the exact TXIDs and addresses you're trying to claim from.

**Comment by juancamilocanal** [comment]
Hi.
TXID: 50ff49358ccfc424bb59e3f27c09985b94bd0b2f8318a396c7e91d69a93a5b85
Wallet: 3LSFNq986MQDK4JxN243mv8UNJFwHsiM4C
