### ISSUE TITLE
BCX issue

### ISSUE THREAD

**Issue by toothyy2** [ymgve/bitcoin_fork_claimer#54]
Hi,

Running the script for BCX gave the following error:

Traceback (most recent call last):
  File "claimer.py", line 1339, in <module>
    txindex, bciscript, satoshis = get_tx_details_from_blockchaininfo(args.txid,             args.srcaddr, coin.hardforkheight)
  File "claimer.py", line 316, in get_tx_details_from_blockchaininfo
    res = urllib2.urlopen("https://blockchain.info/rawtx/%s" % txid)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

Any ideas?

**Comment by ymgve** [comment]
The TXID that was in this issue before you removed it had 65 characters instead of 64 and is therefore not a valid TXID.

**Comment by ymgve** [comment]
It also had an "i" instead of a "1"
