### ISSUE TITLE
Semi success - can claim about half the coins

### ISSUE THREAD

**Issue by sandybradley** [ymgve/bitcoin_fork_claimer#64]
Dear bitcoin forkers,

Thank you for this great script! I have successfully clamied the following coins.

BCX, BCI, BCD, B2X, BTW, LBTC, FBTC, BTP, SBTC, BIFI, BTV

However, I am struggling with the following and would be grateful for any help:

BTN, BTF, BPA, BCA, BTCP, BICC, BTCH, GOD, BEC, BTH, BTT, BCP, WBTC, BCS, BTSQ, BTX

BTN seems to submit the transaction successfully but the balance never shows up.

BPA, BTT, BICC cannot connect to any peer, trying to reconnect 100 times with no luck.

BTX comes back with "Block explorer didn't find any coins at that address" even though the helper scripts find them.

BTF, BCA, GOD, BTH, BEC, WBTC have some sort of destination address issues, returning the below before submission:
Traceback (most recent call last):
  File "claimer.py", line 1394, in <module>
    rawaddr = b58decode(destaddr)
  File "claimer.py", line 68, in b58decode
    n = n * 58 + b58ab.index(c)
ValueError: substring not found

BTCP :
No %s at this address!" % coin.ticker

BTCH:
No BTCH at this address!

My previous bitcoin address:
14q8yEpikK2waeB6NjDAQbPdHbvQYEPfP6

Faithfully,

Alexander

**Comment by Wi11yWank3r** [comment]
You are right about BTN, BPA and BICC. The network is down. You could say those coins died.
BTX recently changed the public key format. That might be a thing.

But some coins you try to claim forked at a time you held no BTC at that address.
I advice you to check out forkdrop.io and pay attention on the forkdate.

**Comment by sandybradley** [comment]
Thank you.

I checked the dates carefully as you suggested.

I managed to get BTX from coinomy wallet and BCBC with an electrum wallet.
I also managed to get WBTC with your script though i'm not sure its worth
anything. I'm still having no luck with BTT, BTH and BTF.

Best

Alexander

**Comment by Wi11yWank3r** [comment]
For the record. I'm not affiliated with the writer of this script. I just use it and I think it's great. I strongly advice not to use native wallets like the BCBC one you mentioned.

The script indeed fails with BTX and BCBC.
BTF no longer has a network and BTH never really was a fork.
BTT is working fine you might do that one again.

**Comment by sandybradley** [comment]
Thanks,

I managed to recover and sell BTF with https://dig.walleting.services/#/

I also managed to get BTT and GOD through the script with BitGo addresses.
Is there anywhere to sell these coins?

Best,

Alexander

**Comment by spindoctor99** [comment]
Hi All 

BTCP have somehow stopped segwit claim spending it was supposed to be fixed by end of july but still nothing.

I have had no luck with SBTC on segwit any tips ???

**Comment by Wi11yWank3r** [comment]
Hi spindocter99

About SBTC. It has been a pain in the ass lately. Are you sure you are using the latest updated version of this script? Segwit should work, though not from a bech32 address.

As for BTCP. I have no notion of BTCP stop claiming from segwit.
There might be something you overlooked. You have to convert your public BTC address in order to claim BTCP with this script. I quote ymgve: "Since BTCP uses the BTCP Electrum servers to check your balance/get transaction details, you need to convert your public BTC address with convert_address.py [your BTC address] BTCP first and use the BTCP address in the script."

Hope this helped.
If not you might want to post your read-out.
I'm not affiliated with the writer of this script.

**Comment by spindoctor99** [comment]
Hi Wi11yWank3r

Thanks heaps for the tips that works great !!

With LBTC because I was segwit does that mean I got nothing ? 
and do you know of some free wallets for BTT / BCBC and some of the other coins  ?

**Comment by Wi11yWank3r** [comment]
LBTC no segwit support. That's right, nothing there.
BTT on vipzbt.com for chinese citizens only and worth virtually nothing.
BCBC used to be traded on trade.multicoins.org but also worth virtually nothing.
You can find this info yourself on forkdrop.io

Glad I could be of help.
