### ISSUE TITLE
BCI fails with "reject" "no-witness-yet"

### ISSUE THREAD

**Issue by keyeh** [ymgve/bitcoin_fork_claimer#72]
I'm attempting to redeem BCI from [AcFsnXQnXFUv8MEkeVmfoMk4yUGW6r1aA1](https://explorer.bitcoininterest.io/address/AcFsnXQnXFUv8MEkeVmfoMk4yUGW6r1aA1)
The corresponding SegWit P2SH(P2WPKH) bitcoin address is 3NB24a3bk199QYjCCwmw56quePdXL6ujue
I'm using the latest script at commit 78e0f5257626dd89a97e3ed6c7a26fd71499713a
I run the command:

```
python claimer.py
BCI
f27f32e58188dbd92d2102fba7d0258b2bb2426b3de9f06568396a3780838529
PRIVATEKEY
AcFsnXQnXFUv8MEkeVmfoMk4yUGW6r1aA1
DESTINATIONADDR
--txindex 855
--satoshis 392733272
```

[Txindex of 855 obtained from here](https://explorer.bitcoininterest.io/api/tx/f27f32e58188dbd92d2102fba7d0258b2bb2426b3de9f06568396a3780838529)

Output of the script:

```
Raw transaction
0100000000010129858380376a396865f0e93d6b42b22b8b25d0a7fb02212dd9db8881e5327ff257030000171600144ad818780fe897179c14e31d7f24cb73d8fd2b9affffffff01709e6817000000001976a914d
4d4e5477b29500945da3fb6dfdded9c25cbcded88ac02483045022100e070ef32d20e92d218ec793546628f33612e31d679e0ac1d9afbf555013399fe022071b940ab7d738e5c6c5dff264e0743973f7e68406730
e072bf1d8a9d15954cf441210241f1436cd10b87a61e64abd06ca45ea2a244c1fbd18a92fd96d251599028ee8300000000

YOU ARE ABOUT TO SEND 3.92733272 BCI (equivalent to 3.92733272 BTC) FROM 3NB24a3bk199QYjCCwmw56quePdXL6ujue
    3.92732272 BCI (equivalent to 3.92732272 BTC) TO iNssizV5hacBE7MpFjwJRk719zt1Nwadq4
!!! 0.00001000 BCI (equivalent to 0.00001000 BTC) WILL BE SENT AS FEES! CONTINUE AT YOUR OWN RISK !!!

Write 'I am sending coins on the Bitcoin Interest network and I accept the risks' to continue
I am sending coins on the Bitcoin Interest network and I accept the risks
generated transaction fb5ecc6d6d315fc931441e79ef3b099115bbaa099e1716aa0d57a77aa74dffbf


Connecting to servers and pushing transaction
Please wait for a minute before stopping the script to see if it entered the server mempool.


Connecting to ('seeder2.bci-server.com', 8334) ... SUCCESS, connected to ('99.42.79.176', 8334)
---> 'version' (93 bytes)
<--- 'version' (113 bytes)
     Version information:
        protocol version 70016
        services 13
        timestamp Sat Oct 20 18:50:08 2018
        user agent '/Bitcoin Interest:0.16.1.1/'
        block height 7880
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'feefilter' (8 bytes)
        server requires minimum fee of 1000 satoshis
        our fee is >= minimum fee, so should be OK
<--- 'getdata' (37 bytes)
        Peer requesting transaction details for fb5ecc6d6d315fc931441e79ef3b099115bbaa099e1716aa0d57a77aa74dffbf
---> 'tx' (218 bytes)
        SENT TRANSACTION: fb5ecc6d6d315fc931441e79ef3b099115bbaa099e1716aa0d57a77aa74dffbf
<--- 'reject' (51 bytes)
'reject' '\x02tx@\x0eno-witness-yet\xbf\xffM\xa7z\xa7W\r\xaa\x16\x17\x9e\t\xaa\xbb\x15\x91\t;\xefy\x1eD1\xc9_1mm\xcc^\xfb'
<--- 'inv' (73 bytes)
        transaction: 66bef478fd60fccf8b4d1120c1ca0f9743fd64ca35f1c603c1dbdaa03a346cba
        transaction: fde0a20465ab01bc2a9c7c8f8d200b3743e05af79f5075d4d74c2ed81fb0ff9f

        Our transaction was not found in the mempool.
        Will retransmit and check again 4 more times.
..........................................................................................
Traceback (most recent call last):
  File "claimer.py", line 1535, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 571, in send_tx
    raise Exception("\tGiving up on transaction. Please verify that the inputs have not already been spent.")
Exception:      Giving up on transaction. Please verify that the inputs have not already been spent.
```

I'm not sure if this is a bug or user error. Some guidance would be appreciated. Thanks!

**Comment by ymgve** [comment]
Seems they have disabled Segwit for the moment on their new "Equinox" restart of their blockchain.
