### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by mogli5278** [ymgve/bitcoin_fork_claimer#83]
Hi I have been running this as per instruction found at https://forkdrop.io/running-bitcoin-fork-claimer-on-windows

I get the following error.
Traceback (most recent call last):
  File "claimer.py", line 1526, in <module>
    rawaddr = b58decode(destaddr)
  File "claimer.py", line 68, in b58decode
    n = n * 58 + b58ab.index(c)
ValueError: substring not found

I have run this using the TAILS linux distribution and also on windows 10. I get the same error on both.
On Windows, I even downgraded Python from the latest to the same version as was used in the forkdrop.io guide. Same error.

Any suggestions?

**Comment by ymgve** [comment]
That happens because the source or destination address isn't a valid base58 or bech32 address. Double check that the order of parameters on the command line is correct. What's the command line you're using? (with data censored)

**Comment by mogli5278** [comment]
Hi ymgve,

Thanks for responding. My command was (with Private data removed)
/c/Python27/python.exe -u claimer.py BCH TXID PK Source_Bitcoin_Address Destination_forkcoin_address --txindex 0 --satoshis 27073431

**Comment by mogli5278** [comment]
I checked both address and the problem is the Destination address. The destination address is an exchange address. I just checked it and it actually had bitcoincash: in front of the address string.
Do I need to include that?

**Comment by ymgve** [comment]
If the part after "bitcoincash:" is all lowercase and numbers, and doesn't start with "1" or "3", it's a new style BCH address that has to be converted, with something like https://bch.btc.com/tools/address-converter

**Comment by mogli5278** [comment]
Great. Thanks.
I found that my exchange offered the same advise and pointed me to the same conversion tool.

Thank you so much for your help.

**Comment by mogli5278** [comment]
Hi ymgve,

Well the above error is gone and I have run the script and received a new error.

These are the last few lines of the script output

Connecting to ('seed.bitprim.org', 8333) ...    Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 9 more times.
Connecting to ('seed.deadalnix.me', 8333) ...   Connection failed with: error(10061, 'No connection could be made because the target machine actively refused it')
        Will retry 8 more times.
Connecting to ('seeder.criptolayer.net', 8333) ...      Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 7 more times.
Connecting to ('seed.bitcoinabc.org', 8333) ...         Connection failed with: gaierror(11002, 'getaddrinfo failed')
        Will retry 6 more times.
Connecting to ('seed-abc.bitcoinforks.org', 8333) ...   Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 5 more times.
Connecting to ('seed.bitprim.org', 8333) ...    Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 4 more times.
Connecting to ('seed.deadalnix.me', 8333) ...   Connection failed with: error(10061, 'No connection could be made because the target machine actively refused it')
        Will retry 3 more times.
Connecting to ('seeder.criptolayer.net', 8333) ...      Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 2 more times.
Connecting to ('seed.bitcoinabc.org', 8333) ...         Connection failed with: gaierror(11002, 'getaddrinfo failed')
        Will retry 1 more times.
Connecting to ('seed-abc.bitcoinforks.org', 8333) ...
Traceback (most recent call last):
  File "claimer.py", line 1637, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "claimer.py", line 466, in send_tx
    self.sc = socket.create_connection(address, 10)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11001] getaddrinfo failed"

Now what is the problem?

**Comment by ymgve** [comment]
Seems like the seed addresses changed in the BCH/ABC split. Try replacing them in the script with these instead: seed.flowee.cash, seed-bch.bitcoinforks.org, btccash-seeder.bitcoinunlimited.info, seed.bchd.cash, seed.bch.loping.net, dnsseed.electroncash.de

Alternatively, you can put the raw transaction hex data that's printed by the script and submit it with https://blockchair.com/broadcast - just be sure to select the Bitcoin Cash network first.

**Comment by mogli5278** [comment]
Ok. I will try
Thanks again

**Comment by mogli5278** [comment]
I updated the script and it is now working just fine.

Thanks for your help. Really appreciate it.
