### ISSUE TITLE
New error: Temporary failure in name resolution

### ISSUE THREAD

**Issue by MrPaz** [ymgve/bitcoin_fork_claimer#84]
I tried using this again after using it successfully a few months ago, but this time I'm getting the following error repeatedly after trying at different times throughout about 24 hours (so doesn't seem temporary).  

```
Querying blockchain.info API about data for transaction <my transaction id>
Traceback (most recent call last):
  File "claimer.py", line 1489, in <module>
    txindex, bciscript, satoshis = get_tx_details_from_blockchaininfo(args.txid, args.srcaddr, coin.hardforkheight)
  File "claimer.py", line 316, in get_tx_details_from_blockchaininfo
    res = urllib2.urlopen("https://blockchain.info/rawtx/%s" % txid)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1248, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1205, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

Any help is appreciated.  Thank you

**Comment by ymgve** [comment]
Seems like an issue with trying to reach blockchain.info - as far as I can see, the endpoint used by the script works fine here, so it must be some problem with the DNS on your machine.

**Comment by MrPaz** [comment]
Ughh, my VPN was apparently getting blocked by blockchain.info.  I turned it off and it worked no problem.  Sorry for the stupid error, but thanks so much for your help!
